DROP TABLE IF EXISTS `{tablename}_cat_count`;
CREATE TABLE IF NOT EXISTS `{tablename}_cat_count` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `catid` int(10) NOT NULL,
  `today_subjects` int(10) NOT NULL,
  `today_replys` int(10) NOT NULL,
  `subjects` int(10) NOT NULL,
  `replys` int(10) NOT NULL,
  `last_title` varchar(255) CHARACTER SET utf8 NOT NULL,
  `last_url` varchar(255) NOT NULL,
  `last_cid` int(10) NOT NULL,
  `last_username` varchar(100) NOT NULL,
  `last_uid` int(10) NOT NULL,
  `last_time` int(10) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `catid` (`catid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='板块统计';

DROP TABLE IF EXISTS `{tablename}_config`;
CREATE TABLE IF NOT EXISTS `{tablename}_config` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `value` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='论坛配置';


INSERT INTO `{tablename}_category` VALUES(1, 0, '0', '官方动态', 'g', 'guanfangdongtai', '', 1, '1,4,5', '', 1, '', 'a:6:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}s:5:\\"admin\\";a:0:{}s:6:\\"member\\";a:0:{}}', 0);
INSERT INTO `{tablename}_category` VALUES(2, 0, '0', '产品交流', 'c', 'chanpinjiaoliu', '', 1, '2,6,7,8,9', '', 1, NULL, 'a:4:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}}', 0);
INSERT INTO `{tablename}_category` VALUES(3, 0, '0', '站长交流', 'z', 'zhanchangjiaoliu', '', 1, '3,10,11', '', 1, NULL, 'a:4:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}}', 0);
INSERT INTO `{tablename}_category` VALUES(4, 1, '0,1', '公告版', 'g', 'gonggaoban', 'guanfangdongtai/', 0, '4', '', 1, '', 'a:6:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}s:5:\\"admin\\";a:0:{}s:6:\\"member\\";a:0:{}}', 0);
INSERT INTO `{tablename}_category` VALUES(5, 1, '0,1', '通知版', 't', 'tongzhiban', 'guanfangdongtai/', 0, '5', '', 1, NULL, 'a:4:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}}', 0);
INSERT INTO `{tablename}_category` VALUES(6, 2, '0,2', '你问我答', 'n', 'niwenwoda', 'chanpinjiaoliu/', 0, '6', '', 1, NULL, 'a:4:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}}', 0);
INSERT INTO `{tablename}_category` VALUES(7, 2, '0,2', '反馈信息', 'f', 'fankuixinxi', 'chanpinjiaoliu/', 0, '7', '', 1, NULL, 'a:4:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}}', 0);
INSERT INTO `{tablename}_category` VALUES(8, 2, '0,2', '发展建议', 'f', 'fazhanjianyi', 'chanpinjiaoliu/', 0, '8', '', 1, NULL, 'a:4:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}}', 0);
INSERT INTO `{tablename}_category` VALUES(9, 2, '0,2', '收费服务', 's', 'shoufeifuwu', 'chanpinjiaoliu/', 0, '9', '', 1, NULL, 'a:4:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}}', 0);
INSERT INTO `{tablename}_category` VALUES(10, 3, '0,3', '交换链接', 'j', 'jiaohuanlianjie', 'zhanchangjiaoliu/', 0, '10', '', 1, NULL, 'a:4:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}}', 0);
INSERT INTO `{tablename}_category` VALUES(11, 3, '0,3', '广告专区', 'g', 'guanggaozhuanqu', 'zhanchangjiaoliu/', 0, '11', '', 1, NULL, 'a:4:{s:4:\\"edit\\";s:1:\\"0\\";s:7:\\"linkurl\\";s:0:\\"\\";s:3:\\"seo\\";a:4:{s:10:\\"show_title\\";s:74:\\"[第{page}页{join}]{title}{join}{catname}{join}{modname}{join}{SITE_NAME}\\";s:10:\\"list_title\\";s:58:\\"[第{page}页{join}]{name}{join}{modname}{join}{SITE_NAME}\\";s:13:\\"list_keywords\\";s:0:\\"\\";s:16:\\"list_description\\";s:0:\\"\\";}s:8:\\"template\\";a:5:{s:8:\\"pagesize\\";s:2:\\"20\\";s:4:\\"show\\";s:9:\\"show.html\\";s:8:\\"category\\";s:13:\\"category.html\\";s:4:\\"list\\";s:9:\\"list.html\\";s:6:\\"search\\";s:11:\\"search.html\\";}}', 0);
